export const APPLICATION_TABLE_HEADERS = [
  'college',
  'constituency_type',
  '? some empty column',
  'email',
  'full_name',
  'nominee_id',
  'major',
  '? some empty column',
  'nickname',
  'nuid',
  'phone_number',
  'phonetic_pronounciation',
  'full_name',
  'pronouns',
  'year',
  'minor',
  'constituency_affiliation_name',
  'constituency_affiliation_type',
  'returning_senator',
  'attestation',
  'semester',
];

export const NOMINATION_TABLE_HEADERS = [
  'college',
  'constituency_affiliation_name',
  '? some empty column',
  'email',
  'full_name',
  'graduation_year',
  'nomination_id',
  'major',
  'nominee',
  'receiveSenatorInfo',
  'status',
];
